Python for Data & Analytics - 2nd Edition<br>
Appendix I - NumPy in Brief

### I.1 About NumPy

In [1]:
import numpy as np

### I.2 Creating a NumPy ndarray

In [2]:
array = np.array([100, 101, 99])
array

array([100, 101,  99])

In [3]:
matrix = np.array([[100, 101, 99], [100, 100.5, 101.1]])
matrix

array([[100. , 101. ,  99. ],
       [100. , 100.5, 101.1]])

In [4]:
matrix0s = np.zeros((3,4))
matrix0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
matrix1s = np.ones((3,4))
matrix1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.random.seed(0)

In [7]:
np.random.randint(0, 10, size=5)

array([5, 0, 3, 3, 7])

In [8]:
np.random.randint(0, 10, size=(2,3))

array([[9, 3, 5],
       [2, 4, 7]])

In [9]:
np.arange(-1.0, 1.5, .5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

### I.3 NumPy Item Data Types

In [10]:
np.zeros((3,4),dtype='float16')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [11]:
np.array([10, 11, np.nan])

array([10., 11., nan])

In [12]:
dates = np.array(['2020-01-01', '2021-01-01', '2022-01-01'],
                 dtype='datetime64[D]')
dates

array(['2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[D]')

In [13]:
dates+7

array(['2020-01-08', '2021-01-08', '2022-01-08'], dtype='datetime64[D]')

In [14]:
np.array([['A', 'phrase'],['Another','phrase']])

array([['A', 'phrase'],
       ['Another', 'phrase']], dtype='<U7')

### I.4 Index and Slicing - Accessing ndarray Items

In [15]:
array[0]

100

In [16]:
matrix[0,1]

101.0

In [17]:
matrix[0,:]

array([100., 101.,  99.])

In [18]:
matrix[:,-1]

array([ 99. , 101.1])

### I.5 Calculations

In [19]:
matrix * 100

array([[10000., 10100.,  9900.],
       [10000., 10050., 10110.]])

In [20]:
balances = np.array([
    [1000, 5000],
    [1500, 3000],
    [1200, 2000]
])

In [21]:
rates = np.array([1, 4])

In [22]:
yearEnd = balances * (1+rates/100)
yearEnd

array([[1010., 5200.],
       [1515., 3120.],
       [1212., 2080.]])

### I.6 An Example - stock price paths

In [23]:
npaths = 6
nperiods = 4

In [24]:
prices = np.zeros((npaths, nperiods))
prices

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
priceStart = 100
for ipath in range(npaths):
   prices[ipath,0] = priceStart

In [26]:
np.random.seed(0)
for iperiod in range(1, nperiods):
   for ipath in range(npaths):
      r = np.random.randint(-1, 2)
      print(r, end=' ')
      prices[ipath, iperiod] = prices[ipath, iperiod-1] * (1+r/100)
   print()
prices

-1 0 -1 0 0 1 
-1 1 -1 -1 -1 1 
0 1 1 -1 0 0 


array([[100.    ,  99.    ,  98.01  ,  98.01  ],
       [100.    , 100.    , 101.    , 102.01  ],
       [100.    ,  99.    ,  98.01  ,  98.9901],
       [100.    , 100.    ,  99.    ,  98.01  ],
       [100.    , 100.    ,  99.    ,  99.    ],
       [100.    , 101.    , 102.01  , 102.01  ]])

In [27]:
prices2 = np.zeros((npaths, nperiods))

In [28]:
prices2[:,0] = priceStart

In [29]:
np.random.seed(0)
for iperiod in range(1, nperiods):
   r = np.random.randint(-1, 2, size=npaths)
   print(r)      
   prices2[:,iperiod] = prices2[:,iperiod-1] * (1+r/100)
#   pass
prices2

[-1  0 -1  0  0  1]
[-1  1 -1 -1 -1  1]
[ 0  1  1 -1  0  0]


array([[100.    ,  99.    ,  98.01  ,  98.01  ],
       [100.    , 100.    , 101.    , 102.01  ],
       [100.    ,  99.    ,  98.01  ,  98.9901],
       [100.    , 100.    ,  99.    ,  98.01  ],
       [100.    , 100.    ,  99.    ,  99.    ],
       [100.    , 101.    , 102.01  , 102.01  ]])

In [30]:
# an example path
prices2[0,:]

array([100.  ,  99.  ,  98.01,  98.01])

In [31]:
# the ending prices across all paths
prices[:,-1]

array([ 98.01  , 102.01  ,  98.9901,  98.01  ,  99.    , 102.01  ])

Code from: Python for Data & Analytics, (c) 2025 Rose River Software, LLC